name: CI Demo

on:
  push:
    branches: [main]

jobs:
  build:
    rush-on: ubuntu-lastest
    steps:
      - uses: actions/checkut@v3
      - name: Test step
        run: echo "CI is running successfully"
